# Name of our action
name: 'Chromatic'
# Event that will trigger the action
on: push

# What the action will do
jobs:
  test:
    # Operating system it will run on
    runs-on: ubuntu-latest
    # List of steps that the action will go through
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - run: yarn test # Adds the test command
        # Adds Chromatic as a step in the workflow
      - uses: chromaui/action@v1
        # Options required for Chromatic's GitHub Action
        with:
          # Chromatic projectToken
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}